#!/bin/bash

echo "runeclipse (from subscript) is deprecated. Instead you should use 'eclrun'."


env | grep -q ECLPATH || (echo "For eclrun to work, you must 'source /prog/res/ecl/script/eclrun.cshrc'" && exit 1)


version_setup=""
queue_setup="-q normal "
program="eclipse"
while [[ $# -gt 0 ]]; do
  case $1 in 
    -p)
      program=$2
      shift
      shift
      ;;
    -i)
      queue_setup=""
      shift
      ;;
    -v)
      version_setup="-v $2 "
      shift
      shift
      ;;
    -x)
      # Assume span is 1 by default in onprem LSF
      shift
      ;;
    -q)
      queue_setup="-q $2 "
      shift
      shift
      ;;
    *)
      datafile=$1
      shift
      ;;
  esac
done

echo
echo "Equivalent command using eclrun:"
echo
echo "> eclrun ${queue_setup}${version_setup}${program} ${datafile}"
